const Map configs = {
  'MEETING_SDK_CLIENT_KEY': 'MeiVfidIQ6iWwn73ZmhJ1Q',
  'MEETING_SDK_CLIENT_SECRET': 'uASjzG3B4xn0V55sGyRpVcq4xzpkmxEQ',
  'SERVER_TO_SERVER_CLIENT_KEY': 'HE55P39hQieQr173X5AJPA',
  'SERVER_TO_SERVER_CLIENT_SECRET': '2UUrWIURAWVkewDab3eX58ncyv8U0yRy',
  'SERVER_TO_SERVER_ACCOUNT_ID': '8O85N72oSfuqdhz0g26KJA'
};